version: '3.8' 

services:

  db:
    image: mysql:8.0
    container_name: mysql_ecom
    restart: unless-stopped
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d:ro  # my folder:dockermagicfolder:mode 
      # nhớ đặt tên file theo thứ tự vì docker chạy theo số thứ tự
volumes: 
  mysql_data: 
